# Generated by Django 4.0.4 on 2022-05-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_link', models.URLField(null=True)),
                ('twitter_link', models.URLField(null=True)),
                ('main_phone', models.CharField(max_length=10)),
                ('dial_code', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=12)),
                ('lon', models.DecimalField(decimal_places=10, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updeted_at', models.DateTimeField(auto_now_add=True)),
                ('detedt_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('main_color', models.CharField(max_length=10)),
                ('full_site_color', models.CharField(max_length=10)),
                ('default_mode', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updeted_at', models.DateTimeField(auto_now_add=True)),
                ('detedt_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageOne', models.URLField()),
                ('imageTwo', models.URLField()),
                ('imageFree', models.URLField()),
                ('titleOne', models.CharField(max_length=255)),
                ('titleTow', models.CharField(max_length=255)),
                ('titleFree', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updeted_at', models.DateTimeField(auto_now_add=True)),
                ('detedt_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
