# Generated by Django 4.0.4 on 2022-05-14 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousePayementPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=True)),
                ('sympbole', models.CharField(max_length=3)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updeted_at', models.DateTimeField(auto_now_add=True)),
                ('detedt_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updeted_at', models.DateTimeField(auto_now_add=True)),
                ('detedt_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.URLField()),
                ('garage_number', models.IntegerField()),
                ('toilLet_number', models.IntegerField()),
                ('address_name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=12)),
                ('lon', models.DecimalField(decimal_places=10, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updeted_at', models.DateTimeField(auto_now_add=True)),
                ('detedt_at', models.DateTimeField(null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_house', to='customers.customer')),
                ('house_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_type_house', to='House.housetype')),
                ('price_payment_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='House.housepayementperiod')),
            ],
        ),
    ]
